### ISSUE TITLE
Update string_view docs

### ISSUE THREAD

**Issue by Lastique** [boostorg/core#100]
The header path is no longer correct:

https://github.com/boostorg/core/blob/12f5f51427fbc9d27f56e5de002b0008fea420c9/doc/string_view.qbk#L15

Also, it would be a good idea to mention that `boost::core::string_view` is not intended to be used by users (hence it is in `detail`) and is supposed to be used by Boost library writers.

**Comment by glenfe** [comment]
I don't think `string_view.qbk` is processed (since it isn't included in `core.qbk`) so no HTML etc. is generated for it.

**Comment by pdimov** [comment]
`string_view.qbk` is no longer included. I just didn't delete it but I will if you insist.

**Comment by Lastique** [comment]
Sorry, I didn't notice the docs were not included.

I don't insist on removing the docs, just asking to make it actual. If you intend to make it available, even if for library maintainers only, it should point to the right headers and provide guidance to the reader. If you're not going to publish the docs, I don't see the point in keeping them, but I'm fine if you want to keep them for some reason.

**Comment by pdimov** [comment]
The future of string views is still unclear, so this documentation might still come into use, once we (Boost) figure out what we want and in which library and namespace we want it.

**Comment by Lastique** [comment]
Ok, feel free to close this if you don't intend to update the docs at the moment.
