### ISSUE TITLE
Add boost::identity to Core?

### ISSUE THREAD

**Issue by denzor200** [boostorg/core#102]
https://en.cppreference.com/w/cpp/utility/functional/identity

Just like `std::identity`, but available in earlier standards.
Why not?

**Comment by pdimov** [comment]
The proper place, in theory, for this would be http://boost.org/libs/functional, although that's a bit outdated now. :-)

**Comment by denzor200** [comment]
> The proper place, in theory, for this would be http://boost.org/libs/functional, although that's a bit outdated now. :-)

Can I create a corresponding pull request to _boost functional_ repository, or should I not?

**Comment by mclow** [comment]
Just saw this; and I think a better place for this is in Boost.Algorithm.

**Comment by glenfe** [comment]
0be868143d53bd582a6ade485b58ed6bb6f38518

**Comment by glenfe** [comment]
https://github.com/boostorg/functional/commit/0be868143d53bd582a6ade485b58ed6bb6f38518
