### ISSUE TITLE
`pointer_traits<void*>::template rebind<int>` is not `int*`

### ISSUE THREAD

**Issue by cmazakas** [boostorg/core#111]
Relevant Compiler Explorer link: https://godbolt.org/z/xo3xKa34e (credit to Ed Catmur on slack)

Boost version is 1.79

It seems like Core's implementation of `pointer_traits` isn't behaving the same as its STL counterpart and is incorrectly producing a `int**` pointer.

**Comment by glenfe** [comment]
Should be addressed in d74140983da3379d08f0a0bfc3dd36fc6d452100 ( following 1e5c86eb9d639404ba1dadd06d0ddb466e7af4b3 )
