### ISSUE TITLE
Please add make_span

### ISSUE THREAD

**Issue by HDembinski** [boostorg/core#125]
span.hpp follows the standard implementation, which does not have make_span, since make_span is superfluous for C++17 onwards. It is very useful to use span with lower C++ standards. Can this please be added?

**Comment by glenfe** [comment]
Will do.

**Comment by HDembinski** [comment]
https://github.com/boostorg/histogram/blob/develop/include/boost/histogram/detail/span.hpp#L252

**Comment by glenfe** [comment]
Also available on develop now
