### ISSUE TITLE
boost::span does not have constructors with iterators

### ISSUE THREAD

**Issue by hadrielk** [boostorg/core#152]
In C++20 `std::span` supports iterator arguments for a couple of its constructor signatures. `boost::span` does not - only raw pointers.

That means one cannot do this:
```cpp
std::vector<int> vec{1,2,3,4};

boost::span<int> sp1(vec.begin(), vec.end()); // error
boost::span<int> sp2(vec.begin(), 2); // error
```

I can provide a PR, if you wish.

**Comment by glenfe** [comment]
See https://github.com/boostorg/core/issues/119

**Comment by hadrielk** [comment]
Oops, I should have looked at the close issues - thanks @glenfe.
