### ISSUE TITLE
error C2039: "_finite": 不是"std"的成员

### ISSUE THREAD

**Issue by liuaifu** [boostorg/core#157]
boost/core/cmath.hpp(239,12): error C2039: "_finite": 不是"std"的成员

boost/core/cmath.hpp(239,12): error C2039: "_finite": is not a member of "std"

Compiled OK after comment "using std::isfinite;"

Windows10 + Boost1.83 + Visual C++ 17.5.2
/std:c++14

**Comment by pdimov** [comment]
You have a `#define isfinite _finite` somewhere.

**Comment by liuaifu** [comment]
This issue has been resolved. It took a while, and I forgot what caused it, but it should be my own mistake anyway.
