### ISSUE TITLE
Add `boost::integer_sequence` and `boost::make_index_sequence`

### ISSUE THREAD

**Issue by denzor200** [boostorg/core#182]
C++11 users need analogues of `std::integer_sequence`, `std::make_index_sequence` and so other template helpers for it.
https://en.cppreference.com/w/cpp/utility/integer_sequence

**Comment by Lastique** [comment]
There is an implementation in [Boost.MP11](https://www.boost.org/doc/libs/1_87_0/libs/mp11/doc/html/mp11.html#integer_sequence).

**Comment by pdimov** [comment]
We also [have one in Compat](https://www.boost.org/doc/libs/1_87_0/libs/compat/doc/html/compat.html#integer_sequence).

**Comment by Lastique** [comment]
> We also [have one in Compat](https://www.boost.org/doc/libs/1_87_0/libs/compat/doc/html/compat.html#integer_sequence).

I'm curious, what was the reason for adding a copy in Boost.Compat?

**Comment by pdimov** [comment]
To not depend on mp11 (which isn't allowed.)
