### ISSUE TITLE
lightweight_test and containers

### ISSUE THREAD

**Issue by breese** [boostorg/core#21]
This issue is to gauge the interest in adding a test macro to lightweight_test for comparing containers. I am using such a macro extensively in my own unit-tests.

The test macro, called `BOOST_TEST_ALL_WITH`, takes the begin and end iterators of two containers plus a predicate. You can see the code [here](https://github.com/breese/core/commit/eb9b8ebf684abe38e723b39ac1736456a36c21f9).

For instance two vectors of ints can be compared with
```
BOOST_TEST_ALL_WITH(input.begin(), input.end(),
                    output.begin(), output.end(),
                    std::equal_to<int>());
```
and two vectors of floats can be approximately compared with
```
const float tolerance = 1e-5;
auto with_tolerance = [tolerance] (decltype(input)::value_type lhs, decltype(output)::value_type rhs)
{
    return (std::fabs(lhs - rhs) <= tolerance);
};
...
BOOST_TEST_ALL_WITH(input.begin(), input.end(),
                    output.begin(), output.end();
                    with_tolerance);
```

**Comment by pdimov** [comment]
Sounds interesting. Wouldn't it be useful to show the actual values though, like BOOST_TEST_EQ does?

**Comment by breese** [comment]
That is a good idea.

I initially wrote the macro without, because I have unit-tests where I compare structs that have an equality operator but no output operator. While these can be added non-intrusively, my structs are really templates (or nested inside templates) so I need to overload the output operator for each combination of template parameters. Not impossible, just inconvenient.

It is for the same reason that I sometimes resort to `BOOST_TEST(x == y)` instead of `BOOST_TEST_EQ(x, y)`.

So maybe we could have one with and one without value printing, or is that overkill?

**Comment by pdimov** [comment]
We could have BOOST_TEST_ALL_EQ, which uses op== and outputs the mismatching values, and BOOST_TEST_ALL_WITH, which uses a predicate and doesn't.

**Comment by Beman** [comment]
On Mon, Jan 30, 2017 at 3:03 PM, Peter Dimov <notifications@github.com>
wrote:

> We could have BOOST_TEST_ALL_EQ, which uses op== and outputs the
> mismatching values, and BOOST_TEST_ALL_WITH, which uses a predicate and
> doesn't.
>
+1

--Beman

**Comment by glenfe** [comment]
Bjorn, looks useful. One comment about the implementation: You label them as Input iterators (template parameter name), but are you assuming that they're Forward iterators?

**Comment by breese** [comment]
@glenfe I used the `InputIterator` concept because that is what `std::mismatch` uses, but you are right that `ForwardIterator` is more correct because I "iterate" twice (first with `std::distance`).

**Comment by breese** [comment]
I have submitted the `BOOST_TEST_ALL_EQ` macro (#26) as described above.

The `BOOST_TEST_ALL_WITH` macro will follow in a later pull request.

Should I add a `BOOST_TEST_WITH` macro for completeness that compares two values with a predicate?

**Comment by pdimov** [comment]
I think that `BOOST_TEST_WITH(x,y,p)` doesn't give anything over `BOOST_TEST(p(x,y))`, so it doesn't look like we need it.

**Comment by breese** [comment]
Good observation about `BOOST_TEST_WITH`. I agree that it is unnecessary.

I have submitted the `BOOST_TEST_ALL_WITH` macro ( #27). It works like `BOOST_TEST_ALL_EQ` with two exceptions: (i) it takes a binary predicate instead of using `operator==`, and (ii) it only outputs mismatching indices, not their values.

The test shows how to use either the binary predicates from `<functional>` or a custom binary predicate.

**Comment by glenfe** [comment]
Since I made a claim on the mailing list about being more diligent about closing GitHub issues that are resolved... :-) Bjørn, any other functionality you want to include as part of this issue?

**Comment by breese** [comment]
I am all set. Thanks for all the review comments.
