### ISSUE TITLE
boost/core/lightweight_test.hpp(118) : warning C4100: 'v' : unreferenced formal parameter

### ISSUE THREAD

**Issue by jeking3** [boostorg/core#36]
See matrix build http://www.boost.org/development/tests/develop/output/teeks99-09-c-win2012R2-64on64-uuid-msvc-10-0-warnings.html#test_uuid

This warning appears many times:

D:\teeks99-09\run\boost_root\boost/core/lightweight_test.hpp(118) : warning C4100: 'v' : unreferenced formal parameter

Seems to be happening on older msvc compilers, before 12.0.

**Comment by pdimov** [comment]
```
inline const void* test_output_impl(std::nullptr_t v) { return v; }
```

Gotta love msvc-10.0.

**Comment by pdimov** [comment]
Should be fixed in https://github.com/boostorg/core/commit/2a3387451fedc1222e9f43e24d300a155295f20d.

**Comment by jeking3** [comment]
Verified.
