### ISSUE TITLE
typo in documentation of boost::combine

### ISSUE THREAD

**Issue by santoshk17** [boostorg/core#44]
[https://www.boost.org/doc/libs/1_68_0/libs/range/doc/html/range/reference/utilities/combine.html](https://www.boost.org/doc/libs/1_68_0/libs/range/doc/html/range/reference/utilities/combine.html)

I would like to fix typo in this boost documentation.

 std::cout << '(' << ti << ',' << **tv** << ')' << '\n';
**tv**  should be **tc**

**Comment by Lastique** [comment]
You should report this to [Boost.Range](https://github.com/boostorg/range/issues/new). Or, preferably, just create a PR.
