### ISSUE TITLE
Add BOOST_TEST_TRAIT_SAME

### ISSUE THREAD

**Issue by HDembinski** [boostorg/core#46]
When testing results of TMP, I very very often do
```
BOOST_TEST_TRAIT_TRUE((std::is_same<Foo, Bar>));
```
It would be nice to have a shortcut macro for this common case.
```
BOOST_TEST_TRAIT_SAME(Foo, Bar);
```

**Comment by pdimov** [comment]
The problem with that is when `Foo` or `Bar` have a comma inside. __VA_ARGS__ but that doesn't always work. Worth thinking about.

**Comment by pdimov** [comment]
Turns out that `__VA_ARGS__` is supported since msvc-8.0, so it could be relied upon nowadays. Added `BOOST_TEST_TRAIT_SAME` on develop.

**Comment by HDembinski** [comment]
Cool, great!

**Comment by HDembinski** [comment]
It seems to work fine on develop, so I am closing this.
