### ISSUE TITLE
move implicit_cast to core?

### ISSUE THREAD

**Issue by HDembinski** [boostorg/core#49]
The boost.conversion library contains `implicit_cast`, which has a simple implementation, no external dependencies and seems useful to have in boost.core. It would also be nice to document the cast better, for me https://stackoverflow.com/questions/868306/what-is-the-difference-between-static-cast-and-implicit-cast was useful to read.

**Comment by anshu-khare-design** [comment]
Hello sir,
I am Anshu Khare and I would like to implement down_cast in boost.core.
Could you please link me to relevant sources?

**Comment by Lastique** [comment]
> Could you please link me to relevant sources?

What sources? This is a Boost.Core issue, this project contains Boost.Core sources.

Also, your post is not related to this issue. Please don't pollute the comments with off-topic.

**Comment by anshu-khare-design** [comment]
Respected sir,
I am really sorry for my comment on the post. I will make sure that it is
not repeated again. This is the first time I am working on GitHub and open
source and I am a novice. I have done courses on C++ and I really wanted to
contribute to the organisation but when I cloned the core library in my
system, I found many cpp and hpp files in different folders. I couldn't get
which file I should look up to for writing the code. I even don't know the
data types which has been used in the library. I have built some programs
related to my courses I have done , locally by writing them from scratch
but i dont know how to build them after cloning projects from github. I
have eclipse installed in my system. I would be really grateful if u could
guide me regarding the same as I am not able to get the proper guidance. I
request you to help me out.
Thank you

**Comment by Lastique** [comment]
These kind of questions should be asked on the mailing list.

**Comment by anshu-khare-design** [comment]
I have worked on this.

**Comment by glenfe** [comment]
@HDembinski I don't think we want to do this. Unlike say, `use_default`, this doesn't exist on public interfaces and is trivial enough to live in detail namespaces if a dependency on Conversion is not desirable. No dependency cycles are broken or would be avoided by relocating this facility.
