### ISSUE TITLE
noinitadaptor::destroy causes compiler error

### ISSUE THREAD

**Issue by SquaredPotato** [boostorg/core#81]
Error states
`/opt/boost/1_74_0/include/boost/core/noinit_adaptor.hpp:58:10: error: expected a class name after '~' to name a destructor  p->~U();`

Compiling on MacOS with Clang 10.0.0., with the -std=c++20 flag.
I'm not sure why, but the error disappear when I replace the template class "U", with any other letter like "T", so that it looks like this:
```
    template<class T>
    void samefunction(T* p) {
        p->~T();
    }
```
instead of
```
    template<class U>
    void samefunction(U* p) {
         p->~U();
    }
```
Is this issue specific to my system? I can't seem to find anyone else having this problem.

EDIT:
Fixed by placing
`#define _TURN_OFF_PLATFORM_STRING` at the top of my main.c file.
Referenced in [cpprestsdk issue 1214](https://github.com/microsoft/cpprestsdk/issues/1214)

**Comment by nperdijk** [comment]
I ran in the same issue as you. Thanks for your edit. That saved my day!
